version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: ./bin/docker_start.sh
    env_file: ./docker/web/.env.docker
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    env_file: ./docker/db/.env_file